ph_idx_to_type = [
    "Aromatic",
    "HydrogenDonor",
    "HydrogenAcceptor",
    "PositiveIon",
    "NegativeIon",
    "Hydrophobic",
    "Halogen",
]
charge_map = [-3, -2, -1, 0, 1, 2, 3, 4, 5]

ph_type_to_idx = {val: idx for idx, val in enumerate(ph_idx_to_type)}

protein_element_map = [
    "C",
    "O",
    "N",
    "S",
    "P",
    "F",
    "H",
    "AS",
    "B",
    "SE",
    "CL",
    "X",
    "I",
    "NE",
    "HG",
    "D",
    "BR",
    "V",
    "BE",
]

lig_atom_type_map = ["C", "H", "N", "O", "F", "P", "S", "Cl", "Br", "I", "B"]
npnde_atom_type_map = [
    "C",
    "N",
    "O",
    "S",
    "F",
    "P",
    "Cl",
    "Br",
    "I",
    "Si",
    "Pd",
    "Ca",
    "Sc",
    "Al",
    "Pt",
    "Cr",
    "Rh",
    "Mo",
    "Y",
    "Cu",
    "Sm",
    "Bi",
    "Ir",
    "Be",
    "Pb",
    "Kr",
    "As",
    "Sn",
    "Lu",
    "Co",
    "Ni",
    "K",
    "Am",
    "Rb",
    "Gd",
    "Ce",
    "Ba",
    "Au",
    "Na",
    "Th",
    "Pr",
    "Yb",
    "Ti",
    "Mg",
    "Sr",
    "Cs",
    "Tl",
    "B",
    "Xe",
    "Cm",
    "Li",
    "Zr",
    "Cf",
    "Ag",
    "Cd",
    "Mn",
    "Eu",
    "In",
    "Hg",
    "W",
    "Tb",
    "La",
    "Sb",
    "Te",
    "Se",
    "Zn",
    "Os",
    "Ga",
    "Fe",
    "Nd",
    "Pu",
    "V",
    "U",
    "Ru",
    "Re",
]

residue_map = [
    "ALA",
    "ILE",
    "TRP",
    "VAL",
    "LYS",
    "ASN",
    "PHE",
    "GLN",
    "SER",
    "GLU",
    "CYS",
    "PRO",
    "GLY",
    "HIS",
    "TYR",
    "ASP",
    "THR",
    "MET",
    "LEU",
    "ARG",
    "UNK", # for unkown residue types
]

# Taken from DrugFlow aa_atom_index
# https://github.com/LPDI-EPFL/DrugFlow/blob/5ad8cd0b2afd6549f21527acc0e00a71a3b7b8db/src/constants.py#L60
protein_atom_map = [
    "CE2",
    "O",
    "CD2",
    "CZ3",
    "CG1",
    "ND2",
    "OE2",
    "NH1",
    "CG",
    "CE3",
    "N",
    "OD1",
    "CD1",
    "CG2",
    "SD",
    "NE",
    "OG",
    "CE1",
    "CZ",
    "NE2",
    "NZ",
    "CA",
    "OH",
    "OG1",
    "CD",
    "SG",
    "NE1",
    "CZ2",
    "OE1",
    "ND1",
    "CB",
    "CH2",
    "CE",
    "C",
    "NH2",
    "OD2",
    "UNK",
]


# cite pdbfixer here
# https://github.com/openmm/pdbfixer/blob/5a6c129fb5b508610542634eafa218fb0e0671fe/pdbfixer/pdbfixer.py#L68
aa_substitutions = {
    "2AS": "ASP",
    "3AH": "HIS",
    "5HP": "GLU",
    "5OW": "LYS",
    "ACL": "ARG",
    "AGM": "ARG",
    "AIB": "ALA",
    "ALM": "ALA",
    "ALO": "THR",
    "ALY": "LYS",
    "ARM": "ARG",
    "ASA": "ASP",
    "ASB": "ASP",
    "ASK": "ASP",
    "ASL": "ASP",
    "ASQ": "ASP",
    "AYA": "ALA",
    "BCS": "CYS",
    "BHD": "ASP",
    "BMT": "THR",
    "BNN": "ALA",
    "BUC": "CYS",
    "BUG": "LEU",
    "C5C": "CYS",
    "C6C": "CYS",
    "CAS": "CYS",
    "CCS": "CYS",
    "CEA": "CYS",
    "CGU": "GLU",
    "CHG": "ALA",
    "CLE": "LEU",
    "CME": "CYS",
    "CSD": "ALA",
    "CSO": "CYS",
    "CSP": "CYS",
    "CSS": "CYS",
    "CSW": "CYS",
    "CSX": "CYS",
    "CXM": "MET",
    "CY1": "CYS",
    "CY3": "CYS",
    "CYG": "CYS",
    "CYM": "CYS",
    "CYQ": "CYS",
    "DAH": "PHE",
    "DAL": "ALA",
    "DAR": "ARG",
    "DAS": "ASP",
    "DCY": "CYS",
    "DGL": "GLU",
    "DGN": "GLN",
    "DHA": "ALA",
    "DHI": "HIS",
    "DIL": "ILE",
    "DIV": "VAL",
    "DLE": "LEU",
    "DLY": "LYS",
    "DNP": "ALA",
    "DPN": "PHE",
    "DPR": "PRO",
    "DSN": "SER",
    "DSP": "ASP",
    "DTH": "THR",
    "DTR": "TRP",
    "DTY": "TYR",
    "DVA": "VAL",
    "EFC": "CYS",
    "FLA": "ALA",
    "FME": "MET",
    "GGL": "GLU",
    "GL3": "GLY",
    "GLZ": "GLY",
    "GMA": "GLU",
    "GSC": "GLY",
    "HAC": "ALA",
    "HAR": "ARG",
    "HIC": "HIS",
    "HIP": "HIS",
    "HMR": "ARG",
    "HPQ": "PHE",
    "HTR": "TRP",
    "HYP": "PRO",
    "IAS": "ASP",
    "IIL": "ILE",
    "IYR": "TYR",
    "KCX": "LYS",
    "LLP": "LYS",
    "LLY": "LYS",
    "LTR": "TRP",
    "LYM": "LYS",
    "LYZ": "LYS",
    "MAA": "ALA",
    "MEN": "ASN",
    "MHS": "HIS",
    "MIS": "SER",
    "MK8": "LEU",
    "MLE": "LEU",
    "MPQ": "GLY",
    "MSA": "GLY",
    "MSE": "MET",
    "MVA": "VAL",
    "NEM": "HIS",
    "NEP": "HIS",
    "NLE": "LEU",
    "NLN": "LEU",
    "NLP": "LEU",
    "NMC": "GLY",
    "OAS": "SER",
    "OCS": "CYS",
    "OMT": "MET",
    "PAQ": "TYR",
    "PCA": "GLU",
    "PEC": "CYS",
    "PHI": "PHE",
    "PHL": "PHE",
    "PR3": "CYS",
    "PRR": "ALA",
    "PTR": "TYR",
    "PYX": "CYS",
    "SAC": "SER",
    "SAR": "GLY",
    "SCH": "CYS",
    "SCS": "CYS",
    "SCY": "CYS",
    "SEL": "SER",
    "SEP": "SER",
    "SET": "SER",
    "SHC": "CYS",
    "SHR": "LYS",
    "SMC": "CYS",
    "SOC": "CYS",
    "STY": "TYR",
    "SVA": "SER",
    "TIH": "ALA",
    "TPL": "TRP",
    "TPO": "THR",
    "TPQ": "ALA",
    "TRG": "LYS",
    "TRO": "TRP",
    "TYB": "TYR",
    "TYI": "TYR",
    "TYQ": "TYR",
    "TYS": "TYR",
    "TYY": "TYR",
}
