B:
  -3:
  - 4
  -2:
  - 4
  -1:
  - 4
  - 2
  - 3
  - 1
  0:
  - 3
  - 2
  - 1
  1:
  - 2
  - 1
Br:
  0:
  - 1
  1:
  - 2
  2:
  - 3
  3:
  - 4
C:
  -3:
  - 1
  -2:
  - 2
  - 1
  -1:
  - 3
  - 2
  - 1
  0:
  - 1
  - 2
  - 3
  - 4
  1:
  - 1
  - 2
  - 3
  - 4
  2:
  - 2
  - 1
Cl:
  0:
  - 1
  1:
  - 2
  - 1
  2:
  - 3
  - 1
  - 2
  3:
  - 4
  - 1
F:
  0:
  - 1
  1:
  - 2
  - 1
  2:
  - 3
H:
  0:
  - 1
I:
  -1:
  - 2
  - 4
  - 1
  - 3
  0:
  - 1
  - 5
  - 3
  - 2
  - 4
  1:
  - 2
  - 1
  - 4
  - 6
  - 5
  2:
  - 3
  - 5
  3:
  - 4
N:
  -2:
  - 1
  -1:
  - 2
  - 1
  0:
  - 2
  - 3
  - 1
  1:
  - 4
  - 3
  - 2
  - 1
  2:
  - 4
  - 5
  - 3
  - 2
  3:
  - 4
  - 3
  - 1
  - 2
  5:
  - 3
O:
  -1:
  - 1
  0:
  - 2
  - 1
  1:
  - 1
  - 2
  2:
  - 4
P:
  -2:
  - 1
  - 5
  -1:
  - 2
  - 1
  - 6
  - 5
  - 4
  - 3
  0:
  - 3
  - 5
  - 2
  - 4
  - 1
  - 6
  - 7
  1:
  - 4
  - 3
  - 2
  - 1
  - 6
  - 5
  2:
  - 7
S:
  -1:
  - 1
  - 5
  - 4
  - 3
  - 2
  0:
  - 2
  - 6
  - 4
  - 1
  - 3
  - 5
  1:
  - 3
  - 2
  - 5
  - 4
  - 1
  - 7
  - 6
  2:
  - 4
